### PR TITLE
Bump js-yaml version to 3.5.2

### PR DESCRIPTION
**Pull request by fritx**
ref #3

### CODE REVIEW

**Comment by okonet** [comment]
Thanks! Is that package following semver? Any breaking changes in there or should I just make a patch release?

**Comment by fritx** [comment]
Ah, sorry. I haven't done any test yet.
Let's hold it on for a while.

**Comment by Zirro** [comment]
I have been using js-yaml 3.5.3 (note that this pull request is for 3.5.2) in a fork of yaml-loader for the past few days and it appears to be working as intended. However, version 3.5.0 introduced a new default behaviour of warning about duplicate keys. Along with this they added an option to revert to the old behaviour of overriding the previous value, but I believe it makes more sense to stick to the default behaviour.

In addition to this, there have been quite a few large releases along the way from 3.0.2 to 3.5.3 which may have affected behaviour in special cases. For these reasons, it is probably a good idea to treat this update as breaking.

**Comment by mderijcke** [comment]
Please commit this and bump semver to 0.2.0

**Comment by fritx** [comment]
:+1: but the latest version of js-yaml is 3.6.0 now (not ^3.5.2)
https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#360--2016-04-16

**Comment by mderijcke** [comment]
That's ok, it won't break people who have `^0.1.0` in their dependencies, that's the beauty of semver

**Comment by okonet** [comment]
I've also enabled greenkeeper on this repository

**Pull request merged**
